-- Initial CourseForge marketplace schema.
-- Generated from prisma/schema.prisma; apply with prisma migrate deploy.
CREATE TYPE "UserRole" AS ENUM ('STUDENT','INSTRUCTOR','ADMIN');
CREATE TYPE "InstructorStatus" AS ENUM ('APPLIED','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED');
CREATE TYPE "CourseStatus" AS ENUM ('DRAFT','IN_REVIEW','PUBLISHED','SUSPENDED','ARCHIVED');
CREATE TYPE "LessonType" AS ENUM ('VIDEO','TEXT','PDF','QUIZ','ASSIGNMENT','LIVE');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING','PAID','REFUNDED','PARTIALLY_REFUNDED','FAILED');
CREATE TYPE "EntitlementStatus" AS ENUM ('ACTIVE','REVOKED','EXPIRED');
CREATE TYPE "PayoutStatus" AS ENUM ('PENDING','PROCESSING','PAID','FAILED','HELD');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"name" TEXT,"role" "UserRole" NOT NULL DEFAULT 'STUDENT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "InstructorProfile" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE,"slug" TEXT NOT NULL UNIQUE,"headline" TEXT,"bio" TEXT,"websiteUrl" TEXT,"expertise" TEXT[],"applicationNote" TEXT,"status" "InstructorStatus" NOT NULL DEFAULT 'APPLIED',"verifiedAt" TIMESTAMP(3),"payoutAccountId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "InstructorProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE TABLE "Course" ("id" TEXT PRIMARY KEY,"instructorId" TEXT NOT NULL,"slug" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"subtitle" TEXT,"description" TEXT NOT NULL,"category" TEXT NOT NULL,"level" TEXT NOT NULL,"status" "CourseStatus" NOT NULL DEFAULT 'DRAFT',"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Course_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "InstructorProfile"("id"));
CREATE TABLE "Section" ("id" TEXT PRIMARY KEY,"courseId" TEXT NOT NULL,"title" TEXT NOT NULL,"position" INTEGER NOT NULL,CONSTRAINT "Section_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE CASCADE,UNIQUE("courseId","position"));
CREATE TABLE "Lesson" ("id" TEXT PRIMARY KEY,"sectionId" TEXT NOT NULL,"title" TEXT NOT NULL,"type" "LessonType" NOT NULL,"position" INTEGER NOT NULL,"isPreview" BOOLEAN NOT NULL DEFAULT false,"contentJson" JSONB,"mediaAssetId" TEXT,"durationSeconds" INTEGER,CONSTRAINT "Lesson_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE CASCADE,UNIQUE("sectionId","position"));
CREATE TABLE "Product" ("id" TEXT PRIMARY KEY,"courseId" TEXT,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "Product_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id"));
CREATE TABLE "Price" ("id" TEXT PRIMARY KEY,"productId" TEXT NOT NULL,"currency" TEXT NOT NULL DEFAULT 'USD',"amountCents" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"providerPriceId" TEXT UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Price_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE);
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'PENDING',"currency" TEXT NOT NULL DEFAULT 'USD',"grossCents" INTEGER NOT NULL,"discountCents" INTEGER NOT NULL DEFAULT 0,"taxCents" INTEGER NOT NULL DEFAULT 0,"netCents" INTEGER NOT NULL,"platformFeeCents" INTEGER NOT NULL DEFAULT 0,"instructorNetCents" INTEGER NOT NULL DEFAULT 0,"paymentProvider" TEXT NOT NULL,"providerPaymentId" TEXT UNIQUE,"acquisitionChannel" TEXT,"paidAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"));
CREATE TABLE "OrderItem" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL,"productId" TEXT NOT NULL,"unitPriceCents" INTEGER NOT NULL,"quantity" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE,CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id"));
CREATE TABLE "Entitlement" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL,"userId" TEXT NOT NULL,"productId" TEXT NOT NULL,"status" "EntitlementStatus" NOT NULL DEFAULT 'ACTIVE',"startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Entitlement_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id"),CONSTRAINT "Entitlement_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"),CONSTRAINT "Entitlement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id"),UNIQUE("orderId","productId"));
CREATE INDEX "Entitlement_userId_status_idx" ON "Entitlement"("userId","status");
CREATE TABLE "Enrollment" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"entitlementId" TEXT UNIQUE,"enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "Enrollment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"),CONSTRAINT "Enrollment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id"),CONSTRAINT "Enrollment_entitlementId_fkey" FOREIGN KEY ("entitlementId") REFERENCES "Entitlement"("id"),UNIQUE("userId","courseId"));
CREATE TABLE "LessonProgress" ("id" TEXT PRIMARY KEY,"enrollmentId" TEXT NOT NULL,"lessonId" TEXT NOT NULL,"completedAt" TIMESTAMP(3),"playbackSeconds" INTEGER NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "LessonProgress_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment"("id") ON DELETE CASCADE,CONSTRAINT "LessonProgress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE,UNIQUE("enrollmentId","lessonId"));
CREATE TABLE "Review" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"rating" INTEGER NOT NULL,"body" TEXT,"verifiedEnrollment" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Review_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"),CONSTRAINT "Review_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id"),UNIQUE("userId","courseId"));
CREATE TABLE "Payout" ("id" TEXT PRIMARY KEY,"instructorId" TEXT NOT NULL,"status" "PayoutStatus" NOT NULL DEFAULT 'PENDING',"amountCents" INTEGER NOT NULL,"currency" TEXT NOT NULL DEFAULT 'USD',"periodStart" TIMESTAMP(3) NOT NULL,"periodEnd" TIMESTAMP(3) NOT NULL,"providerTransferId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Payout_instructorId_fkey" FOREIGN KEY ("instructorId") REFERENCES "InstructorProfile"("id"));
CREATE TABLE "WebhookEvent" ("id" TEXT PRIMARY KEY,"provider" TEXT NOT NULL,"providerEventId" TEXT NOT NULL,"eventType" TEXT NOT NULL,"processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("provider","providerEventId"));
